# The filtered local position (e.g. fused computer vision and accelerometers). Coordinate frame is right-handed, Z-axis down (aeronautical frame, NED / north-east-down convention)

Header header
uint32 time_boot_ms    # Timestamp (milliseconds since system boot)
float64  x	       # X position
float64  y	       # Y positon
float64  z	       # Z position
float64  vx	       # Ground X Speed 
float64  vy	       # Ground Y Speed 
float64  vz	       # Ground Z Speed 
